=== MDSD-Tools/JaMoPP/bundles/tools.mdsd.jamopp.model.java.test/resources/TimeSheetGenerator-main/examples/schemas/month.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"definitions": {
		"time_span": {
			"type": "string",
			"pattern": "^[0-9]+:[0-5]?[0-9]$"
		},
		"day_time": {
			"type": "string",
			"pattern": "^(([0-1]?[0-9])|(2[0-3])):[0-5]?[0-9]$"
		},
		"entry": {
			"type": "object",
			"properties": {
				"action": {
					"type": "string"
				},
				"day": {
					"type": "integer",
					"minimum": 1,
					"maximum": 31
				},
				"start": {
					"$ref": "#/definitions/day_time"
				},
				"end": {
					"$ref": "#/definitions/day_time"
				},
				"pause": {
					"$ref": "#/definitions/time_span"
				},
				"vacation": {
					"type": "boolean",
					"default": false
				}
			},
			"required": ["action", "day", "start", "end"],
			"not": { "required": ["pause", "vacation"] },
			"additionalProperties": false
		}
	},
	"properties": {
		"year": {
			"type": "integer",
			"minimum": 1000,
			"maximum": 9999
		},
		"month": {
			"type": "integer",
			"minimum": 1,
			"maximum": 12
		},
		"pred_transfer": {
			"$ref": "#/definitions/time_span"
		},
		"succ_transfer": {
			"$ref": "#/definitions/time_span"
		},
		"entries": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/entry"
			}
		}
	},
	"patternProperties": {
		"^\\$.*$": {}
	},
	"required": ["year", "month", "entries"],
	"additionalProperties": false
}

=== MDSD-Tools/JaMoPP/bundles/tools.mdsd.jamopp.model.java.test/resources/TimeSheetGenerator-main/examples/Example_month.json
{
  "$schema": "https://raw.githubusercontent.com/kit-sdq/TimeSheetGenerator/master/examples/schemas/month.json",
  "year": 2019,
  "month": 11,
  "pred_transfer": "0:00",
  "succ_transfer": "0:00",
  "entries": [
    {"action": "Korrektur", "day": 2, "start": "10:00", "end": "11:00"},
    {"action": "Fragen beantworten", "day": 4, "start": "11:31", "end": "15:11", "pause": "00:30"},
    {"action": "Urlaub in Italien", "day": 11, "start": "08:00", "end": "16:00", "vacation": true}
  ]
}
